// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4twRb6-U8BzHZphQQJKhXKUSEsCsytEA',
    appId: '1:61361535090:web:c8af924435e103f09b2aeb',
    messagingSenderId: '61361535090',
    projectId: 'arav-app-b60d4',
    authDomain: 'arav-app-b60d4.firebaseapp.com',
    storageBucket: 'arav-app-b60d4.firebasestorage.app',
    measurementId: 'G-WXWJXHX7J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA26_f0PD_M0sd-4qS3n_2_JFict7B1ofk',
    appId: '1:61361535090:android:46a43762beda47309b2aeb',
    messagingSenderId: '61361535090',
    projectId: 'arav-app-b60d4',
    storageBucket: 'arav-app-b60d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5UJYtRVSh547wbr44WsiM16DYpIDtCjs',
    appId: '1:61361535090:ios:787aef4284985ce39b2aeb',
    messagingSenderId: '61361535090',
    projectId: 'arav-app-b60d4',
    storageBucket: 'arav-app-b60d4.firebasestorage.app',
    iosClientId: '61361535090-fpepfug2hgt5ekldtphfoadfmdpro409.apps.googleusercontent.com',
    iosBundleId: 'com.example.arva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5UJYtRVSh547wbr44WsiM16DYpIDtCjs',
    appId: '1:61361535090:ios:787aef4284985ce39b2aeb',
    messagingSenderId: '61361535090',
    projectId: 'arav-app-b60d4',
    storageBucket: 'arav-app-b60d4.firebasestorage.app',
    iosClientId: '61361535090-fpepfug2hgt5ekldtphfoadfmdpro409.apps.googleusercontent.com',
    iosBundleId: 'com.example.arva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4twRb6-U8BzHZphQQJKhXKUSEsCsytEA',
    appId: '1:61361535090:web:445639760a2d42489b2aeb',
    messagingSenderId: '61361535090',
    projectId: 'arav-app-b60d4',
    authDomain: 'arav-app-b60d4.firebaseapp.com',
    storageBucket: 'arav-app-b60d4.firebasestorage.app',
    measurementId: 'G-KQV3S0LFE9',
  );
}
